# Generated by Django 4.2.9 on 2024-02-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Estudante',
        ),
    ]
