# Generated by Django 4.2.9 on 2024-02-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_alter_estudante_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
